#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: auth-service
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/auth/**
#
#        - id: post-producer
#          uri: lb://POST-PRODUCER
#          predicates:
#            - Path=/post/**
#          filters:
#            - AuthFilter
#
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/**
#          filters:
#            - AuthFilter
#
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins:
#              - "http://127.0.0.1:5173"
#              - "http://localhost:5173"
#            allowed-headers:
#              - "*"
#            allowed-methods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#              - OPTION
#            allow-credentials: true
#            max-age: 3600
#
#  main:
#    web-application-type: reactive
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      database: 0
#      username: default
#      password: 4kTtH2ddXfN2sFmXE6sowOLukxiaJhN8n
#server:
#  port: 8765
#eureka:
#  instance:
#    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post/**
          filters:
            - AuthFilter

        - id: post-producer
          uri: lb://POST-PRODUCER
          predicates:
            - Path=/post-create/**
          filters:
            - AuthFilter

        - id: like-service
          uri: lb://LIKE-SERVICE
          predicates:
            - Path=/like/**
          filters:
            - AuthFilter

        - id: like-producer
          uri: lb://LIKE-PRODUCER
          predicates:
            - Path=/like-create/**
          filters:
            - AuthFilter

        - id: follow-service
          uri: lb://FOLLOW-SERVICE
          predicates:
            - Path=/follow/**
          filters:
            - AuthFilter

        - id: follow-producer
          uri: lb://FOLLOW-PRODUCER
          predicates:
            - Path=/follow-create/**
          filters:
            - AuthFilter
      globalcors:
        cors-configurations:
                  '[/**]':
                    allowed-origins:
                      - "http://127.0.0.1:5173"
                      - "http://localhost:5173"
                    allowed-headers:
                      - "*"
                    allowed-methods:
                      - GET
                      - POST
                      - DELETE
                      - PUT
                      - OPTION
                    allow-credentials: true
                    max-age: 3600
  main:
    web-application-type: reactive
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      username: default
      password: 4kTtH2ddXfN2sFmXE6sowOLukxiaJhN8n

server:
  port: 8765


eureka:
  instance:
    hostname: localhost