spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: postGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  application:
    name: post-consumer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kafkademo
    username: postgres
    password: root
server:
  port: 8091
eureka:
  instance:
    hostname: localhost